USE QLGH
GO
iF EXISTS (SELECT * FROM sys.server_principals WHERE name = 'AD_01' AND type = 'S')
BEGIN 
    IF EXISTS (select * from sys.database_principals WHERE type IN ('S', 'U') and name = 'AD_01')
    BEGIN
        EXEC('DROP USER AD_01')
    END
    EXEC('DROP LOGIN ' + 'AD_01')
END 
GO
create LOGIN AD_01 WITH PASSWORD = '123456'
CREATE USER AD_01 FOR LOGIN AD_01
GO
GRANT SELECT, UPDATE, INSERT, DELETE TO AD_01 WITH GRANT OPTION
ALTER ROLE db_accessadmin ADD MEMBER AD_01
GO
--------------------------------------- create role
IF NOT EXISTS (SELECT * FROM SYS.database_principals WHERE TYPE = 'R' AND name = 'R_NHAN_VIEN')
BEGIN
    CREATE ROLE R_NHAN_VIEN
END 

IF NOT EXISTS (SELECT * FROM SYS.database_principals WHERE TYPE = 'R' AND name = 'R_DOI_TAC')
BEGIN
    CREATE ROLE R_DOI_TAC
END 

IF NOT EXISTS (SELECT * FROM SYS.database_principals WHERE TYPE = 'R' AND name = 'R_KHACH_HANG')
BEGIN
    CREATE ROLE R_KHACH_HANG
END 

IF NOT EXISTS (SELECT * FROM SYS.database_principals WHERE TYPE = 'R' AND name = 'R_TAI_XE')
BEGIN
    CREATE ROLE R_TAI_XE
END 

--------------------------------------- Permission roles
-- Permission R_NHAN_VIEN
GRANT SELECT, UPDATE, INSERT, DELETE ON DON_DK TO R_NHAN_VIEN
GRANT SELECT, UPDATE, INSERT, DELETE ON HOPDONG TO R_NHAN_VIEN
GRANT SELECT, UPDATE, INSERT, DELETE ON CHINHANH TO R_NHAN_VIEN
GRANT SELECT ON NHANVIEN TO R_NHAN_VIEN
-- Permission R_DOI_TAC
GRANT SELECT, UPDATE ON CHINHANH TO R_DOI_TAC
GRANT SELECT, UPDATE, INSERT, DELETE ON THUCDON_DA TO R_DOI_TAC
GRANT SELECT, UPDATE, INSERT, DELETE ON THUCDON_DU TO R_DOI_TAC
GRANT SELECT, UPDATE, INSERT, DELETE ON MONAN TO R_DOI_TAC
GRANT SELECT, UPDATE, INSERT, DELETE ON DOUONG TO R_DOI_TAC
GRANT SELECT, UPDATE, INSERT, DELETE ON TT_MA_CN TO R_DOI_TAC
GRANT SELECT, UPDATE, INSERT, DELETE ON TT_DU_CN TO R_DOI_TAC
GRANT SELECT, UPDATE, INSERT, DELETE ON TOPING_DA TO R_DOI_TAC
GRANT SELECT, UPDATE, INSERT, DELETE ON TOPING_DU TO R_DOI_TAC
GRANT SELECT, UPDATE ON DONHANG TO R_DOI_TAC
GRANT SELECT ON CHITIET_DH_DA TO R_DOI_TAC
GRANT SELECT ON CHITIET_DH_DU TO R_DOI_TAC
GRANT SELECT ON TUYCHON_DA_DH TO R_DOI_TAC
GRANT SELECT ON TUYCHON_DU_DH TO R_DOI_TAC
GRANT SELECT ON DANH_GIA_DON_HANG TO R_DOI_TAC
GRANT SELECT ON HOPDONG TO R_DOI_TAC

--Permission R_KHACH_HANG
GRANT SELECT, UPDATE, INSERT ON DONHANG TO R_KHACH_HANG
GRANT SELECT ON CHINHANH TO R_KHACH_HANG
GRANT SELECT ON THUCDON_DA TO R_KHACH_HANG
GRANT SELECT ON THUCDON_DU TO R_KHACH_HANG
GRANT SELECT ON MONAN TO R_KHACH_HANG
GRANT SELECT ON DOUONG TO R_KHACH_HANG
GRANT SELECT ON TT_MA_CN TO R_KHACH_HANG
GRANT SELECT ON TT_DU_CN TO R_KHACH_HANG
GRANT SELECT ON TOPING_DA TO R_KHACH_HANG
GRANT SELECT ON TOPING_DU TO R_KHACH_HANG
GRANT SELECT, INSERT, UPDATE, DELETE ON CHITIET_DH_DA TO R_KHACH_HANG
GRANT SELECT, INSERT, UPDATE, DELETE ON CHITIET_DH_DU TO R_KHACH_HANG
GRANT SELECT, INSERT ON DANH_GIA_DON_HANG TO R_KHACH_HANG

-- Permission R_TAI_XE
GRANT SELECT, UPDATE ON TAIXE TO R_TAI_XE
GRANT SELECT, UPDATE ON DONHANG TO R_TAI_XE
GRANT SELECT ON CHINHANH TO R_TAI_XE

------------------------------------------------ PROCEDURE CREATE LOGIN
GO
CREATE PROCEDURE P_CreateLoginAndUser
    @username VARCHAR(50),
    @password VARCHAR(50),
    @Role VARCHAR(50)
AS
BEGIN
    IF NOT EXISTS(SELECT * FROM SYS.database_principals WHERE TYPE = 'R' AND name = @Role)
    BEGIN   
        PRINT N'ROLE NOT EXISTS'
        RETURN 0
    END 
    -- Check if the login already exists
    IF EXISTS (SELECT * FROM sys.server_principals WHERE name = @username AND type = 'S')
    BEGIN
        EXEC('DROP LOGIN ' + @username )
    END

    IF EXISTS (select * from sys.database_principals WHERE type IN ('S', 'U') and name = @username)
    BEGIN
        EXEC('DROP USER '+ @username)
    END
    EXEC('CREATE LOGIN ' + @username + ' WITH PASSWORD = ''' + @password + '''');
    EXEC('CREATE USER ' + @username + ' FOR LOGIN ' + @username)
    EXEC('ALTER ROLE '+ @Role +' ADD MEMBER ' + @username)
    PRINT 'Login created successfully.';
END

--- CREATE LOGIN ACCOUNT NHAN_VIEN
EXEC P_CreateLoginAndUser 'NV_01 ', '123456', 'R_NHAN_VIEN'
EXEC P_CreateLoginAndUser 'NV_02 ', '123456', 'R_NHAN_VIEN'
EXEC P_CreateLoginAndUser 'NV_03 ', '123456', 'R_NHAN_VIEN'
EXEC P_CreateLoginAndUser 'NV_04 ', '123456', 'R_NHAN_VIEN'
EXEC P_CreateLoginAndUser 'NV_05 ', '123456', 'R_NHAN_VIEN'
--- CREATE LOGIN ACCOUNT DOI_TAC
EXEC P_CreateLoginAndUser 'DT_01', '123456', 'R_DOI_TAC'
EXEC P_CreateLoginAndUser 'DT_02', '123456', 'R_DOI_TAC'
--- CREATE LOGIN ACCOUNT TAI_XE
EXEC P_CreateLoginAndUser 'TX_01', '123456', 'R_TAI_XE'
EXEC P_CreateLoginAndUser 'TX_02', '123456', 'R_TAI_XE'
EXEC P_CreateLoginAndUser 'TX_03', '123456', 'R_TAI_XE'
EXEC P_CreateLoginAndUser 'TX_04', '123456', 'R_TAI_XE'
--- CREATE LOGIN ACCOUNT KHACH_HANG
EXEC P_CreateLoginAndUser 'KH_01', '123456', 'R_KHACH_HANG'
EXEC P_CreateLoginAndUser 'KH_02', '123456', 'R_KHACH_HANG'
EXEC P_CreateLoginAndUser 'KH_03', '123456', 'R_KHACH_HANG'
EXEC P_CreateLoginAndUser 'KH_04', '123456', 'R_KHACH_HANG'